//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'JsonDataSample'.</summary>
	[Serializable]
	[DataContract]
	public partial class JsonDataSample
	{
		/// <summary>Gets or sets the CreateBy field. Derived from Entity Model Field 'JsonDataSample.CreateBy'</summary>
		[DataMember]
		public System.String CreateBy { get; set; }
		/// <summary>Gets or sets the CreateDate field. Derived from Entity Model Field 'JsonDataSample.CreateDate'</summary>
		[DataMember]
		public Nullable<System.DateTime> CreateDate { get; set; }
		/// <summary>Gets or sets the FileName field. Derived from Entity Model Field 'JsonDataSample.FileName'</summary>
		[DataMember]
		public System.String FileName { get; set; }
		/// <summary>Gets or sets the FilePath field. Derived from Entity Model Field 'JsonDataSample.FilePath'</summary>
		[DataMember]
		public System.String FilePath { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'JsonDataSample.Id'</summary>
		[DataMember]
		public System.String Id { get; set; }
		/// <summary>Gets or sets the JsonData field. Derived from Entity Model Field 'JsonDataSample.JsonData'</summary>
		[DataMember]
		public System.String JsonData { get; set; }
		/// <summary>Gets or sets the UpdateBy field. Derived from Entity Model Field 'JsonDataSample.UpdateBy'</summary>
		[DataMember]
		public System.String UpdateBy { get; set; }
		/// <summary>Gets or sets the UpdateDate field. Derived from Entity Model Field 'JsonDataSample.UpdateDate'</summary>
		[DataMember]
		public Nullable<System.DateTime> UpdateDate { get; set; }
	}

}




