//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'PdfSync'.</summary>
	[Serializable]
	[DataContract]
	public partial class PdfSync
	{
		/// <summary>Gets or sets the DateCreate field. Derived from Entity Model Field 'PdfSync.DateCreate'</summary>
		[DataMember]
		public Nullable<System.DateTime> DateCreate { get; set; }
		/// <summary>Gets or sets the DateModify field. Derived from Entity Model Field 'PdfSync.DateModify'</summary>
		[DataMember]
		public Nullable<System.DateTime> DateModify { get; set; }
		/// <summary>Gets or sets the ErrorMessage field. Derived from Entity Model Field 'PdfSync.ErrorMessage'</summary>
		[DataMember]
		public System.String ErrorMessage { get; set; }
		/// <summary>Gets or sets the FilePath field. Derived from Entity Model Field 'PdfSync.FilePath'</summary>
		[DataMember]
		public System.String FilePath { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'PdfSync.Id'</summary>
		[DataMember]
		public System.String Id { get; set; }
		/// <summary>Gets or sets the JsonData field. Derived from Entity Model Field 'PdfSync.JsonData'</summary>
		[DataMember]
		public System.String JsonData { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'PdfSync.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Status field. Derived from Entity Model Field 'PdfSync.Status'</summary>
		[DataMember]
		public System.String Status { get; set; }
		/// <summary>Gets or sets the UserCreate field. Derived from Entity Model Field 'PdfSync.UserCreate'</summary>
		[DataMember]
		public System.String UserCreate { get; set; }
		/// <summary>Gets or sets the UserModify field. Derived from Entity Model Field 'PdfSync.UserModify'</summary>
		[DataMember]
		public System.String UserModify { get; set; }
	}

}




