//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'SyncTime'.</summary>
	[Serializable]
	[DataContract]
	public partial class SyncTime
	{
		/// <summary>Gets or sets the Destination field. Derived from Entity Model Field 'SyncTime.Destination'</summary>
		[DataMember]
		public System.String Destination { get; set; }
		/// <summary>Gets or sets the ErrorMessage field. Derived from Entity Model Field 'SyncTime.ErrorMessage'</summary>
		[DataMember]
		public System.String ErrorMessage { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'SyncTime.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the RequestTime field. Derived from Entity Model Field 'SyncTime.RequestTime'</summary>
		[DataMember]
		public Nullable<System.DateTime> RequestTime { get; set; }
		/// <summary>Gets or sets the Status field. Derived from Entity Model Field 'SyncTime.Status'</summary>
		[DataMember]
		public Nullable<System.Boolean> Status { get; set; }
	}

}




