//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Doc2PdfApi.HelperClasses;
using Doc2PdfApi.FactoryClasses;
using Doc2PdfApi.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Doc2PdfApi.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'dboJsonDataSample'.<br/><br/></summary>
	[Serializable]
	public partial class dboJsonDataSampleEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static dboJsonDataSampleEntityStaticMetaData _staticMetaData = new dboJsonDataSampleEntityStaticMetaData();
		private static dboJsonDataSampleRelations _relationsFactory = new dboJsonDataSampleRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class dboJsonDataSampleEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public dboJsonDataSampleEntityStaticMetaData()
			{
				SetEntityCoreInfo("dboJsonDataSampleEntity", InheritanceHierarchyType.None, false, (int)Doc2PdfApi.EntityType.dboJsonDataSampleEntity, typeof(dboJsonDataSampleEntity), typeof(dboJsonDataSampleEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static dboJsonDataSampleEntity()
		{
		}

		/// <summary> CTor</summary>
		public dboJsonDataSampleEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public dboJsonDataSampleEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this dboJsonDataSampleEntity</param>
		public dboJsonDataSampleEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboJsonDataSample which data should be fetched into this dboJsonDataSample object</param>
		public dboJsonDataSampleEntity(System.String id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboJsonDataSample which data should be fetched into this dboJsonDataSample object</param>
		/// <param name="validator">The custom validator object for this dboJsonDataSampleEntity</param>
		public dboJsonDataSampleEntity(System.String id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected dboJsonDataSampleEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this dboJsonDataSampleEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static dboJsonDataSampleRelations Relations { get { return _relationsFactory; } }

		/// <summary>The CreateBy property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."createBy".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 30.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CreateBy
		{
			get { return (System.String)GetValue((int)dboJsonDataSampleFieldIndex.CreateBy, true); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.CreateBy, value); }
		}

		/// <summary>The CreateDate property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."createDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreateDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)dboJsonDataSampleFieldIndex.CreateDate, false); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.CreateDate, value); }
		}

		/// <summary>The FileName property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."FileName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String FileName
		{
			get { return (System.String)GetValue((int)dboJsonDataSampleFieldIndex.FileName, true); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.FileName, value); }
		}

		/// <summary>The FilePath property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."FilePath".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String FilePath
		{
			get { return (System.String)GetValue((int)dboJsonDataSampleFieldIndex.FilePath, true); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.FilePath, value); }
		}

		/// <summary>The Id property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."Id".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 40.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Id
		{
			get { return (System.String)GetValue((int)dboJsonDataSampleFieldIndex.Id, true); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.Id, value); }
		}

		/// <summary>The JsonData property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."jsonData".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String JsonData
		{
			get { return (System.String)GetValue((int)dboJsonDataSampleFieldIndex.JsonData, true); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.JsonData, value); }
		}

		/// <summary>The UpdateBy property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."updateBy".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 30.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String UpdateBy
		{
			get { return (System.String)GetValue((int)dboJsonDataSampleFieldIndex.UpdateBy, true); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.UpdateBy, value); }
		}

		/// <summary>The UpdateDate property of the Entity dboJsonDataSample<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JSON_DATA_SAMPLE"."updateDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdateDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)dboJsonDataSampleFieldIndex.UpdateDate, false); }
			set { SetValue((int)dboJsonDataSampleFieldIndex.UpdateDate, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Doc2PdfApi
{
	public enum dboJsonDataSampleFieldIndex
	{
		///<summary>CreateBy. </summary>
		CreateBy,
		///<summary>CreateDate. </summary>
		CreateDate,
		///<summary>FileName. </summary>
		FileName,
		///<summary>FilePath. </summary>
		FilePath,
		///<summary>Id. </summary>
		Id,
		///<summary>JsonData. </summary>
		JsonData,
		///<summary>UpdateBy. </summary>
		UpdateBy,
		///<summary>UpdateDate. </summary>
		UpdateDate,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Doc2PdfApi.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: dboJsonDataSample. </summary>
	public partial class dboJsonDataSampleRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticdboJsonDataSampleRelations
	{

		/// <summary>CTor</summary>
		static StaticdboJsonDataSampleRelations() { }
	}
}
