//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Doc2PdfApi.HelperClasses;
using Doc2PdfApi.FactoryClasses;
using Doc2PdfApi.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Doc2PdfApi.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'dboPdfSync'.<br/><br/></summary>
	[Serializable]
	public partial class dboPdfSyncEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static dboPdfSyncEntityStaticMetaData _staticMetaData = new dboPdfSyncEntityStaticMetaData();
		private static dboPdfSyncRelations _relationsFactory = new dboPdfSyncRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class dboPdfSyncEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public dboPdfSyncEntityStaticMetaData()
			{
				SetEntityCoreInfo("dboPdfSyncEntity", InheritanceHierarchyType.None, false, (int)Doc2PdfApi.EntityType.dboPdfSyncEntity, typeof(dboPdfSyncEntity), typeof(dboPdfSyncEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static dboPdfSyncEntity()
		{
		}

		/// <summary> CTor</summary>
		public dboPdfSyncEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public dboPdfSyncEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this dboPdfSyncEntity</param>
		public dboPdfSyncEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboPdfSync which data should be fetched into this dboPdfSync object</param>
		public dboPdfSyncEntity(System.String id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for dboPdfSync which data should be fetched into this dboPdfSync object</param>
		/// <param name="validator">The custom validator object for this dboPdfSyncEntity</param>
		public dboPdfSyncEntity(System.String id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected dboPdfSyncEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this dboPdfSyncEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static dboPdfSyncRelations Relations { get { return _relationsFactory; } }

		/// <summary>The DateCreate property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."dateCreate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DateCreate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)dboPdfSyncFieldIndex.DateCreate, false); }
			set { SetValue((int)dboPdfSyncFieldIndex.DateCreate, value); }
		}

		/// <summary>The DateModify property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."dateModify".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DateModify
		{
			get { return (Nullable<System.DateTime>)GetValue((int)dboPdfSyncFieldIndex.DateModify, false); }
			set { SetValue((int)dboPdfSyncFieldIndex.DateModify, value); }
		}

		/// <summary>The ErrorMessage property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."Error_message".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ErrorMessage
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.ErrorMessage, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.ErrorMessage, value); }
		}

		/// <summary>The FilePath property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."FilePath".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String FilePath
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.FilePath, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.FilePath, value); }
		}

		/// <summary>The Id property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."Id".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Id
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.Id, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.Id, value); }
		}

		/// <summary>The JsonData property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."jsonData".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String JsonData
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.JsonData, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.JsonData, value); }
		}

		/// <summary>The Name property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.Name, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.Name, value); }
		}

		/// <summary>The Status property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."Status".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Status
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.Status, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.Status, value); }
		}

		/// <summary>The UserCreate property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."userCreate".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String UserCreate
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.UserCreate, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.UserCreate, value); }
		}

		/// <summary>The UserModify property of the Entity dboPdfSync<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Pdf_Sync"."userModify".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String UserModify
		{
			get { return (System.String)GetValue((int)dboPdfSyncFieldIndex.UserModify, true); }
			set { SetValue((int)dboPdfSyncFieldIndex.UserModify, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Doc2PdfApi
{
	public enum dboPdfSyncFieldIndex
	{
		///<summary>DateCreate. </summary>
		DateCreate,
		///<summary>DateModify. </summary>
		DateModify,
		///<summary>ErrorMessage. </summary>
		ErrorMessage,
		///<summary>FilePath. </summary>
		FilePath,
		///<summary>Id. </summary>
		Id,
		///<summary>JsonData. </summary>
		JsonData,
		///<summary>Name. </summary>
		Name,
		///<summary>Status. </summary>
		Status,
		///<summary>UserCreate. </summary>
		UserCreate,
		///<summary>UserModify. </summary>
		UserModify,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Doc2PdfApi.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: dboPdfSync. </summary>
	public partial class dboPdfSyncRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticdboPdfSyncRelations
	{

		/// <summary>CTor</summary>
		static StaticdboPdfSyncRelations() { }
	}
}
