//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Doc2PdfApi.HelperClasses;
using Doc2PdfApi.FactoryClasses;
using Doc2PdfApi.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Doc2PdfApi.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'SyncTime'.<br/><br/></summary>
	[Serializable]
	public partial class SyncTimeEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SyncTimeEntityStaticMetaData _staticMetaData = new SyncTimeEntityStaticMetaData();
		private static SyncTimeRelations _relationsFactory = new SyncTimeRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SyncTimeEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SyncTimeEntityStaticMetaData()
			{
				SetEntityCoreInfo("SyncTimeEntity", InheritanceHierarchyType.None, false, (int)Doc2PdfApi.EntityType.SyncTimeEntity, typeof(SyncTimeEntity), typeof(SyncTimeEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SyncTimeEntity()
		{
		}

		/// <summary> CTor</summary>
		public SyncTimeEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SyncTimeEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SyncTimeEntity</param>
		public SyncTimeEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SyncTime which data should be fetched into this SyncTime object</param>
		public SyncTimeEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SyncTime which data should be fetched into this SyncTime object</param>
		/// <param name="validator">The custom validator object for this SyncTimeEntity</param>
		public SyncTimeEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SyncTimeEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SyncTimeEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SyncTimeRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Destination property of the Entity SyncTime<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Sync_Time"."Destination".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Destination
		{
			get { return (System.String)GetValue((int)SyncTimeFieldIndex.Destination, true); }
			set { SetValue((int)SyncTimeFieldIndex.Destination, value); }
		}

		/// <summary>The ErrorMessage property of the Entity SyncTime<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Sync_Time"."Error_message".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ErrorMessage
		{
			get { return (System.String)GetValue((int)SyncTimeFieldIndex.ErrorMessage, true); }
			set { SetValue((int)SyncTimeFieldIndex.ErrorMessage, value); }
		}

		/// <summary>The Id property of the Entity SyncTime<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Sync_Time"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SyncTimeFieldIndex.Id, true); }
			set { SetValue((int)SyncTimeFieldIndex.Id, value); }
		}

		/// <summary>The RequestTime property of the Entity SyncTime<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Sync_Time"."Request_time".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> RequestTime
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SyncTimeFieldIndex.RequestTime, false); }
			set { SetValue((int)SyncTimeFieldIndex.RequestTime, value); }
		}

		/// <summary>The Status property of the Entity SyncTime<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Sync_Time"."Status".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> Status
		{
			get { return (Nullable<System.Boolean>)GetValue((int)SyncTimeFieldIndex.Status, false); }
			set { SetValue((int)SyncTimeFieldIndex.Status, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Doc2PdfApi
{
	public enum SyncTimeFieldIndex
	{
		///<summary>Destination. </summary>
		Destination,
		///<summary>ErrorMessage. </summary>
		ErrorMessage,
		///<summary>Id. </summary>
		Id,
		///<summary>RequestTime. </summary>
		RequestTime,
		///<summary>Status. </summary>
		Status,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Doc2PdfApi.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SyncTime. </summary>
	public partial class SyncTimeRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSyncTimeRelations
	{

		/// <summary>CTor</summary>
		static StaticSyncTimeRelations() { }
	}
}
