//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using Doc2PdfApi.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.LinqSupportClasses.DTOProjectionHelpers;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Dtos.Persistence
{

	/// <summary>Static class for (extension) methods for fetching and projecting instances of Dtos.DtoClasses.SyncTime from the entity model.</summary>
	public static partial class SyncTimePersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Doc2PdfApi.EntityClasses.SyncTimeEntity, Dtos.DtoClasses.SyncTime>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Doc2PdfApi.EntityClasses.SyncTimeEntity, Dtos.DtoClasses.SyncTime> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToSyncTime(System.Linq.IQueryable{Doc2PdfApi.EntityClasses.SyncTimeEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToSyncTime(ref System.Linq.Expressions.Expression<Func<Doc2PdfApi.EntityClasses.SyncTimeEntity, Dtos.DtoClasses.SyncTime>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToSyncTime(EntityQuery{Doc2PdfApi.EntityClasses.SyncTimeEntity}, Doc2PdfApi.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToSyncTime(EntityQuery{Doc2PdfApi.EntityClasses.SyncTimeEntity}, Doc2PdfApi.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToSyncTimeQs(ref System.Linq.Expressions.Expression<Func<Dtos.DtoClasses.SyncTime>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static SyncTimePersistence() { }
	
		/// <summary>Extension method which produces a projection to Dtos.DtoClasses.SyncTime which instances are projected from the results of the specified baseQuery, which returns Doc2PdfApi.EntityClasses.SyncTimeEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve Dtos.DtoClasses.SyncTime instances</returns>
		public static IQueryable<Dtos.DtoClasses.SyncTime> ProjectToSyncTime(this IQueryable<Doc2PdfApi.EntityClasses.SyncTimeEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to Dtos.DtoClasses.SyncTime which instances are projected from the results of the specified baseQuery using QuerySpec, which returns Doc2PdfApi.EntityClasses.SyncTimeEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve Dtos.DtoClasses.SyncTime instances</returns>
		public static DynamicQuery<Dtos.DtoClasses.SyncTime> ProjectToSyncTime(this EntityQuery<Doc2PdfApi.EntityClasses.SyncTimeEntity> baseQuery, Doc2PdfApi.FactoryClasses.QueryFactory qf)
		{
			System.Linq.Expressions.Expression<Func<Dtos.DtoClasses.SyncTime>> projectionAdjustments = null;
			GetAdjustmentsForProjectToSyncTimeQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ"))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new Dtos.DtoClasses.SyncTime()
				{
					Destination = SyncTimeFields.Destination.Source("__BQ").ToValue<System.String>(),
					ErrorMessage = SyncTimeFields.ErrorMessage.Source("__BQ").ToValue<System.String>(),
					Id = SyncTimeFields.Id.Source("__BQ").ToValue<System.Int32>(),
					RequestTime = SyncTimeFields.RequestTime.Source("__BQ").ToValue<Nullable<System.DateTime>>(),
					Status = SyncTimeFields.Status.Source("__BQ").ToValue<Nullable<System.Boolean>>(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_SyncTime 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to Dtos.DtoClasses.SyncTime which instances are projected from the Doc2PdfApi.EntityClasses.SyncTimeEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Doc2PdfApi.EntityClasses.SyncTimeEntity instance created from the specified entity instance</returns>
		public static Dtos.DtoClasses.SyncTime ProjectToSyncTime(this Doc2PdfApi.EntityClasses.SyncTimeEntity entity)
		{
			return _compiledProjector(entity);
		}

		private static System.Linq.Expressions.Expression<Func<Doc2PdfApi.EntityClasses.SyncTimeEntity, Dtos.DtoClasses.SyncTime>> CreateProjectionFunc()
		{
			System.Linq.Expressions.Expression<Func<Doc2PdfApi.EntityClasses.SyncTimeEntity, Dtos.DtoClasses.SyncTime>> mainProjection = p__0 => new Dtos.DtoClasses.SyncTime()
			{
				Destination = p__0.Destination,
				ErrorMessage = p__0.ErrorMessage,
				Id = p__0.Id,
				RequestTime = p__0.RequestTime,
				Status = p__0.Status,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_SyncTime 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<Doc2PdfApi.EntityClasses.SyncTimeEntity, Dtos.DtoClasses.SyncTime>> projectionAdjustments = null;
			GetAdjustmentsForProjectToSyncTime(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


