//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Doc2PdfApi.HelperClasses
{
	/// <summary>Field Creation Class for entity dboJsonDataSampleEntity</summary>
	public partial class dboJsonDataSampleFields
	{
		/// <summary>Creates a new dboJsonDataSampleEntity.CreateBy field instance</summary>
		public static EntityField2 CreateBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.CreateBy); }}
		/// <summary>Creates a new dboJsonDataSampleEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.CreateDate); }}
		/// <summary>Creates a new dboJsonDataSampleEntity.FileName field instance</summary>
		public static EntityField2 FileName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.FileName); }}
		/// <summary>Creates a new dboJsonDataSampleEntity.FilePath field instance</summary>
		public static EntityField2 FilePath { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.FilePath); }}
		/// <summary>Creates a new dboJsonDataSampleEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.Id); }}
		/// <summary>Creates a new dboJsonDataSampleEntity.JsonData field instance</summary>
		public static EntityField2 JsonData { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.JsonData); }}
		/// <summary>Creates a new dboJsonDataSampleEntity.UpdateBy field instance</summary>
		public static EntityField2 UpdateBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.UpdateBy); }}
		/// <summary>Creates a new dboJsonDataSampleEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboJsonDataSampleFieldIndex.UpdateDate); }}
	}

	/// <summary>Field Creation Class for entity dboPdfSyncEntity</summary>
	public partial class dboPdfSyncFields
	{
		/// <summary>Creates a new dboPdfSyncEntity.DateCreate field instance</summary>
		public static EntityField2 DateCreate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.DateCreate); }}
		/// <summary>Creates a new dboPdfSyncEntity.DateModify field instance</summary>
		public static EntityField2 DateModify { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.DateModify); }}
		/// <summary>Creates a new dboPdfSyncEntity.ErrorMessage field instance</summary>
		public static EntityField2 ErrorMessage { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.ErrorMessage); }}
		/// <summary>Creates a new dboPdfSyncEntity.FilePath field instance</summary>
		public static EntityField2 FilePath { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.FilePath); }}
		/// <summary>Creates a new dboPdfSyncEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.Id); }}
		/// <summary>Creates a new dboPdfSyncEntity.JsonData field instance</summary>
		public static EntityField2 JsonData { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.JsonData); }}
		/// <summary>Creates a new dboPdfSyncEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.Name); }}
		/// <summary>Creates a new dboPdfSyncEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.Status); }}
		/// <summary>Creates a new dboPdfSyncEntity.UserCreate field instance</summary>
		public static EntityField2 UserCreate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.UserCreate); }}
		/// <summary>Creates a new dboPdfSyncEntity.UserModify field instance</summary>
		public static EntityField2 UserModify { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboPdfSyncFieldIndex.UserModify); }}
	}

	/// <summary>Field Creation Class for entity dboSyncTimeEntity</summary>
	public partial class dboSyncTimeFields
	{
		/// <summary>Creates a new dboSyncTimeEntity.Destination field instance</summary>
		public static EntityField2 Destination { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboSyncTimeFieldIndex.Destination); }}
		/// <summary>Creates a new dboSyncTimeEntity.ErrorMessage field instance</summary>
		public static EntityField2 ErrorMessage { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboSyncTimeFieldIndex.ErrorMessage); }}
		/// <summary>Creates a new dboSyncTimeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboSyncTimeFieldIndex.Id); }}
		/// <summary>Creates a new dboSyncTimeEntity.RequestTime field instance</summary>
		public static EntityField2 RequestTime { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboSyncTimeFieldIndex.RequestTime); }}
		/// <summary>Creates a new dboSyncTimeEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(dboSyncTimeFieldIndex.Status); }}
	}

	/// <summary>Field Creation Class for entity JsonDataSampleEntity</summary>
	public partial class JsonDataSampleFields
	{
		/// <summary>Creates a new JsonDataSampleEntity.CreateBy field instance</summary>
		public static EntityField2 CreateBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.CreateBy); }}
		/// <summary>Creates a new JsonDataSampleEntity.CreateDate field instance</summary>
		public static EntityField2 CreateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.CreateDate); }}
		/// <summary>Creates a new JsonDataSampleEntity.FileName field instance</summary>
		public static EntityField2 FileName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.FileName); }}
		/// <summary>Creates a new JsonDataSampleEntity.FilePath field instance</summary>
		public static EntityField2 FilePath { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.FilePath); }}
		/// <summary>Creates a new JsonDataSampleEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.Id); }}
		/// <summary>Creates a new JsonDataSampleEntity.JsonData field instance</summary>
		public static EntityField2 JsonData { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.JsonData); }}
		/// <summary>Creates a new JsonDataSampleEntity.UpdateBy field instance</summary>
		public static EntityField2 UpdateBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.UpdateBy); }}
		/// <summary>Creates a new JsonDataSampleEntity.UpdateDate field instance</summary>
		public static EntityField2 UpdateDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(JsonDataSampleFieldIndex.UpdateDate); }}
	}

	/// <summary>Field Creation Class for entity PdfSyncEntity</summary>
	public partial class PdfSyncFields
	{
		/// <summary>Creates a new PdfSyncEntity.DateCreate field instance</summary>
		public static EntityField2 DateCreate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.DateCreate); }}
		/// <summary>Creates a new PdfSyncEntity.DateModify field instance</summary>
		public static EntityField2 DateModify { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.DateModify); }}
		/// <summary>Creates a new PdfSyncEntity.ErrorMessage field instance</summary>
		public static EntityField2 ErrorMessage { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.ErrorMessage); }}
		/// <summary>Creates a new PdfSyncEntity.FilePath field instance</summary>
		public static EntityField2 FilePath { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.FilePath); }}
		/// <summary>Creates a new PdfSyncEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.Id); }}
		/// <summary>Creates a new PdfSyncEntity.JsonData field instance</summary>
		public static EntityField2 JsonData { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.JsonData); }}
		/// <summary>Creates a new PdfSyncEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.Name); }}
		/// <summary>Creates a new PdfSyncEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.Status); }}
		/// <summary>Creates a new PdfSyncEntity.UserCreate field instance</summary>
		public static EntityField2 UserCreate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.UserCreate); }}
		/// <summary>Creates a new PdfSyncEntity.UserModify field instance</summary>
		public static EntityField2 UserModify { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PdfSyncFieldIndex.UserModify); }}
	}

	/// <summary>Field Creation Class for entity SyncTimeEntity</summary>
	public partial class SyncTimeFields
	{
		/// <summary>Creates a new SyncTimeEntity.Destination field instance</summary>
		public static EntityField2 Destination { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SyncTimeFieldIndex.Destination); }}
		/// <summary>Creates a new SyncTimeEntity.ErrorMessage field instance</summary>
		public static EntityField2 ErrorMessage { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SyncTimeFieldIndex.ErrorMessage); }}
		/// <summary>Creates a new SyncTimeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SyncTimeFieldIndex.Id); }}
		/// <summary>Creates a new SyncTimeEntity.RequestTime field instance</summary>
		public static EntityField2 RequestTime { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SyncTimeFieldIndex.RequestTime); }}
		/// <summary>Creates a new SyncTimeEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SyncTimeFieldIndex.Status); }}
	}
	

}