//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Doc2PdfApi.FactoryClasses;
using Doc2PdfApi.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Doc2PdfApi.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitdboJsonDataSampleEntityInfo();
			InitdboPdfSyncEntityInfo();
			InitdboSyncTimeEntityInfo();
			InitJsonDataSampleEntityInfo();
			InitPdfSyncEntityInfo();
			InitSyncTimeEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits dboJsonDataSampleEntity's info objects</summary>
		private void InitdboJsonDataSampleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboJsonDataSampleFieldIndex), "dboJsonDataSampleEntity");
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "CreateBy", typeof(System.String), false, false, false, true,  (int)dboJsonDataSampleFieldIndex.CreateBy, 30, 0, 0);
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "CreateDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)dboJsonDataSampleFieldIndex.CreateDate, 0, 0, 0);
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "FileName", typeof(System.String), false, false, false, true,  (int)dboJsonDataSampleFieldIndex.FileName, 2147483647, 0, 0);
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "FilePath", typeof(System.String), false, false, false, true,  (int)dboJsonDataSampleFieldIndex.FilePath, 2147483647, 0, 0);
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "Id", typeof(System.String), true, false, false, false,  (int)dboJsonDataSampleFieldIndex.Id, 40, 0, 0);
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "JsonData", typeof(System.String), false, false, false, true,  (int)dboJsonDataSampleFieldIndex.JsonData, 2147483647, 0, 0);
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "UpdateBy", typeof(System.String), false, false, false, true,  (int)dboJsonDataSampleFieldIndex.UpdateBy, 30, 0, 0);
			this.AddElementFieldInfo("dboJsonDataSampleEntity", "UpdateDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)dboJsonDataSampleFieldIndex.UpdateDate, 0, 0, 0);
		}

		/// <summary>Inits dboPdfSyncEntity's info objects</summary>
		private void InitdboPdfSyncEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboPdfSyncFieldIndex), "dboPdfSyncEntity");
			this.AddElementFieldInfo("dboPdfSyncEntity", "DateCreate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)dboPdfSyncFieldIndex.DateCreate, 0, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "DateModify", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)dboPdfSyncFieldIndex.DateModify, 0, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "ErrorMessage", typeof(System.String), false, false, false, true,  (int)dboPdfSyncFieldIndex.ErrorMessage, 2147483647, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "FilePath", typeof(System.String), false, false, false, true,  (int)dboPdfSyncFieldIndex.FilePath, 200, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "Id", typeof(System.String), true, false, false, false,  (int)dboPdfSyncFieldIndex.Id, 50, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "JsonData", typeof(System.String), false, false, false, true,  (int)dboPdfSyncFieldIndex.JsonData, 2147483647, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "Name", typeof(System.String), false, false, false, true,  (int)dboPdfSyncFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "Status", typeof(System.String), false, false, false, true,  (int)dboPdfSyncFieldIndex.Status, 10, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "UserCreate", typeof(System.String), false, false, false, true,  (int)dboPdfSyncFieldIndex.UserCreate, 50, 0, 0);
			this.AddElementFieldInfo("dboPdfSyncEntity", "UserModify", typeof(System.String), false, false, false, true,  (int)dboPdfSyncFieldIndex.UserModify, 50, 0, 0);
		}

		/// <summary>Inits dboSyncTimeEntity's info objects</summary>
		private void InitdboSyncTimeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(dboSyncTimeFieldIndex), "dboSyncTimeEntity");
			this.AddElementFieldInfo("dboSyncTimeEntity", "Destination", typeof(System.String), false, false, false, true,  (int)dboSyncTimeFieldIndex.Destination, 100, 0, 0);
			this.AddElementFieldInfo("dboSyncTimeEntity", "ErrorMessage", typeof(System.String), false, false, false, true,  (int)dboSyncTimeFieldIndex.ErrorMessage, 2147483647, 0, 0);
			this.AddElementFieldInfo("dboSyncTimeEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)dboSyncTimeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("dboSyncTimeEntity", "RequestTime", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)dboSyncTimeFieldIndex.RequestTime, 0, 0, 0);
			this.AddElementFieldInfo("dboSyncTimeEntity", "Status", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)dboSyncTimeFieldIndex.Status, 0, 0, 0);
		}

		/// <summary>Inits JsonDataSampleEntity's info objects</summary>
		private void InitJsonDataSampleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(JsonDataSampleFieldIndex), "JsonDataSampleEntity");
			this.AddElementFieldInfo("JsonDataSampleEntity", "CreateBy", typeof(System.String), false, false, false, true,  (int)JsonDataSampleFieldIndex.CreateBy, 30, 0, 0);
			this.AddElementFieldInfo("JsonDataSampleEntity", "CreateDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)JsonDataSampleFieldIndex.CreateDate, 0, 0, 0);
			this.AddElementFieldInfo("JsonDataSampleEntity", "FileName", typeof(System.String), false, false, false, true,  (int)JsonDataSampleFieldIndex.FileName, 2147483647, 0, 0);
			this.AddElementFieldInfo("JsonDataSampleEntity", "FilePath", typeof(System.String), false, false, false, true,  (int)JsonDataSampleFieldIndex.FilePath, 2147483647, 0, 0);
			this.AddElementFieldInfo("JsonDataSampleEntity", "Id", typeof(System.String), true, false, false, false,  (int)JsonDataSampleFieldIndex.Id, 40, 0, 0);
			this.AddElementFieldInfo("JsonDataSampleEntity", "JsonData", typeof(System.String), false, false, false, true,  (int)JsonDataSampleFieldIndex.JsonData, 2147483647, 0, 0);
			this.AddElementFieldInfo("JsonDataSampleEntity", "UpdateBy", typeof(System.String), false, false, false, true,  (int)JsonDataSampleFieldIndex.UpdateBy, 30, 0, 0);
			this.AddElementFieldInfo("JsonDataSampleEntity", "UpdateDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)JsonDataSampleFieldIndex.UpdateDate, 0, 0, 0);
		}

		/// <summary>Inits PdfSyncEntity's info objects</summary>
		private void InitPdfSyncEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PdfSyncFieldIndex), "PdfSyncEntity");
			this.AddElementFieldInfo("PdfSyncEntity", "DateCreate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)PdfSyncFieldIndex.DateCreate, 0, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "DateModify", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)PdfSyncFieldIndex.DateModify, 0, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "ErrorMessage", typeof(System.String), false, false, false, true,  (int)PdfSyncFieldIndex.ErrorMessage, 2147483647, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "FilePath", typeof(System.String), false, false, false, true,  (int)PdfSyncFieldIndex.FilePath, 200, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "Id", typeof(System.String), true, false, false, false,  (int)PdfSyncFieldIndex.Id, 50, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "JsonData", typeof(System.String), false, false, false, true,  (int)PdfSyncFieldIndex.JsonData, 2147483647, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "Name", typeof(System.String), false, false, false, true,  (int)PdfSyncFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "Status", typeof(System.String), false, false, false, true,  (int)PdfSyncFieldIndex.Status, 10, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "UserCreate", typeof(System.String), false, false, false, true,  (int)PdfSyncFieldIndex.UserCreate, 50, 0, 0);
			this.AddElementFieldInfo("PdfSyncEntity", "UserModify", typeof(System.String), false, false, false, true,  (int)PdfSyncFieldIndex.UserModify, 50, 0, 0);
		}

		/// <summary>Inits SyncTimeEntity's info objects</summary>
		private void InitSyncTimeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SyncTimeFieldIndex), "SyncTimeEntity");
			this.AddElementFieldInfo("SyncTimeEntity", "Destination", typeof(System.String), false, false, false, true,  (int)SyncTimeFieldIndex.Destination, 100, 0, 0);
			this.AddElementFieldInfo("SyncTimeEntity", "ErrorMessage", typeof(System.String), false, false, false, true,  (int)SyncTimeFieldIndex.ErrorMessage, 2147483647, 0, 0);
			this.AddElementFieldInfo("SyncTimeEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)SyncTimeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("SyncTimeEntity", "RequestTime", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)SyncTimeFieldIndex.RequestTime, 0, 0, 0);
			this.AddElementFieldInfo("SyncTimeEntity", "Status", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)SyncTimeFieldIndex.Status, 0, 0, 0);
		}
	}
}