//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Doc2PdfApi.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal partial class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitdboJsonDataSampleEntityMappings();
			InitdboPdfSyncEntityMappings();
			InitdboSyncTimeEntityMappings();
			InitJsonDataSampleEntityMappings();
			InitPdfSyncEntityMappings();
			InitSyncTimeEntityMappings();
		}

		/// <summary>Inits dboJsonDataSampleEntity's mappings</summary>
		private void InitdboJsonDataSampleEntityMappings()
		{
			this.AddElementMapping("dboJsonDataSampleEntity", @"violet", @"dbo", "JSON_DATA_SAMPLE", 8, 0);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "CreateBy", "createBy", true, "VarChar", 30, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "CreateDate", "createDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "FileName", "FileName", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "FilePath", "FilePath", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "Id", "Id", false, "VarChar", 40, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "JsonData", "jsonData", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "UpdateBy", "updateBy", true, "VarChar", 30, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("dboJsonDataSampleEntity", "UpdateDate", "updateDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 7);
		}

		/// <summary>Inits dboPdfSyncEntity's mappings</summary>
		private void InitdboPdfSyncEntityMappings()
		{
			this.AddElementMapping("dboPdfSyncEntity", @"violet", @"dbo", "Pdf_Sync", 10, 0);
			this.AddElementFieldMapping("dboPdfSyncEntity", "DateCreate", "dateCreate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("dboPdfSyncEntity", "DateModify", "dateModify", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("dboPdfSyncEntity", "ErrorMessage", "Error_message", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("dboPdfSyncEntity", "FilePath", "FilePath", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("dboPdfSyncEntity", "Id", "Id", false, "VarChar", 50, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("dboPdfSyncEntity", "JsonData", "jsonData", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("dboPdfSyncEntity", "Name", "Name", true, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("dboPdfSyncEntity", "Status", "Status", true, "VarChar", 10, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("dboPdfSyncEntity", "UserCreate", "userCreate", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("dboPdfSyncEntity", "UserModify", "userModify", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 9);
		}

		/// <summary>Inits dboSyncTimeEntity's mappings</summary>
		private void InitdboSyncTimeEntityMappings()
		{
			this.AddElementMapping("dboSyncTimeEntity", @"violet", @"dbo", "Sync_Time", 5, 0);
			this.AddElementFieldMapping("dboSyncTimeEntity", "Destination", "Destination", true, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("dboSyncTimeEntity", "ErrorMessage", "Error_message", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("dboSyncTimeEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("dboSyncTimeEntity", "RequestTime", "Request_time", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("dboSyncTimeEntity", "Status", "Status", true, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 4);
		}

		/// <summary>Inits JsonDataSampleEntity's mappings</summary>
		private void InitJsonDataSampleEntityMappings()
		{
			this.AddElementMapping("JsonDataSampleEntity", @"violet", @"dbo", "JSON_DATA_SAMPLE", 8, 0);
			this.AddElementFieldMapping("JsonDataSampleEntity", "CreateBy", "createBy", true, "VarChar", 30, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("JsonDataSampleEntity", "CreateDate", "createDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("JsonDataSampleEntity", "FileName", "FileName", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("JsonDataSampleEntity", "FilePath", "FilePath", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("JsonDataSampleEntity", "Id", "Id", false, "VarChar", 40, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("JsonDataSampleEntity", "JsonData", "jsonData", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("JsonDataSampleEntity", "UpdateBy", "updateBy", true, "VarChar", 30, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("JsonDataSampleEntity", "UpdateDate", "updateDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 7);
		}

		/// <summary>Inits PdfSyncEntity's mappings</summary>
		private void InitPdfSyncEntityMappings()
		{
			this.AddElementMapping("PdfSyncEntity", @"violet", @"dbo", "Pdf_Sync", 10, 0);
			this.AddElementFieldMapping("PdfSyncEntity", "DateCreate", "dateCreate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("PdfSyncEntity", "DateModify", "dateModify", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("PdfSyncEntity", "ErrorMessage", "Error_message", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("PdfSyncEntity", "FilePath", "FilePath", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("PdfSyncEntity", "Id", "Id", false, "VarChar", 50, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("PdfSyncEntity", "JsonData", "jsonData", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("PdfSyncEntity", "Name", "Name", true, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("PdfSyncEntity", "Status", "Status", true, "VarChar", 10, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("PdfSyncEntity", "UserCreate", "userCreate", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("PdfSyncEntity", "UserModify", "userModify", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 9);
		}

		/// <summary>Inits SyncTimeEntity's mappings</summary>
		private void InitSyncTimeEntityMappings()
		{
			this.AddElementMapping("SyncTimeEntity", @"violet", @"dbo", "Sync_Time", 5, 0);
			this.AddElementFieldMapping("SyncTimeEntity", "Destination", "Destination", true, "NVarChar", 100, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SyncTimeEntity", "ErrorMessage", "Error_message", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SyncTimeEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("SyncTimeEntity", "RequestTime", "Request_time", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("SyncTimeEntity", "Status", "Status", true, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 4);
		}

	}
}
