//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Doc2PdfApi
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>dboJsonDataSample</summary>
		dboJsonDataSampleEntity,
		///<summary>dboPdfSync</summary>
		dboPdfSyncEntity,
		///<summary>dboSyncTime</summary>
		dboSyncTimeEntity,
		///<summary>JsonDataSample</summary>
		JsonDataSampleEntity,
		///<summary>PdfSync</summary>
		PdfSyncEntity,
		///<summary>SyncTime</summary>
		SyncTimeEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

